"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bell, CalendarDays, ChartColumnIncreasing, CheckCircle2, ChevronDown, ChartNoAxesColumnIncreasing, Banknote, DatabaseBackup, FileText, Info, MoreHorizontal, Package, Percent, RefreshCw, Wallet } from 'lucide-react';
import { DashboardPeriod, Comparison, Resolution, comparisonFromSearch, comparisonPeriod, quickPeriod, validPeriod } from '@/lib/dashboard-period';
import { businessTrend, ExecutiveDocument, executiveModel, financialReport, metricDelta } from '@/lib/executive-dashboard';
import { useExpenseReport } from './useExpenseReport';
import { DashboardCharts, Spark } from './DashboardCharts';
import { DashboardDetail, Detail } from './DashboardDetail';
import { money, shortDate, rangeText, types, statuses } from './presentation';
import s from './ExecutiveDashboard.module.css';

export type ExpenseFocus = { category?: string; expenseClass?: string };
type Props = { documents: ExecutiveDocument[]; period: DashboardPeriod; onPeriod: (period: DashboardPeriod) => void;
  loadedAt: string | null; onExpenses: (focus?: ExpenseFocus) => void; onDocuments: (type: string, id?: string) => void; onExport: () => void; onRefresh?: () => void };
const comparisons: Record<Comparison, string> = { previous: 'ช่วงก่อนหน้า', month: 'เดือนก่อน', year: 'ช่วงเดียวกันปีก่อน', none: 'ไม่เปรียบเทียบ' };
function Help({ children }: { children: string }) { return <details className={s.help}><summary aria-label="คำอธิบาย"><Info size={14}/></summary><p>{children}</p></details>; }
function Delta({ current, previous, margin=false, inverse=false, enabled }: { current:number|null;previous:number|null;margin?:boolean;inverse?:boolean;enabled:boolean }) {
  const delta=metricDelta(current,previous,margin);
  if(!enabled)return <span className={s.muted}>ไม่เปรียบเทียบ</span>;
  if(!delta)return <span className={s.muted}>ข้อมูลเปรียบเทียบไม่พร้อม</span>;
  return <span className={(inverse?delta.difference<=0:delta.difference>=0)?s.positive:s.negative}>{delta.difference>0?<ArrowUp size={14}/>:delta.difference<0?<ArrowDown size={14}/>:null}
    {margin?`${delta.points!>0?'+':''}${delta.points!.toFixed(1)} จุด`:delta.percent!==null?`${delta.percent>0?'+':''}${delta.percent.toFixed(1)}%`:`${delta.difference>=0?'+':''}${money(delta.difference)}`}
    {!margin&&delta.percent===null&&<small> ฐานเดิม ≤ 0</small>}</span>;
}

export default function ExecutiveDashboard({ documents, period, onPeriod, loadedAt, onExpenses, onDocuments, onExport, onRefresh }:Props) {
  const [comparison,setComparison]=useState<Comparison>(()=>typeof window==='undefined'?'previous':comparisonFromSearch(location.search));
  const [resolution,setResolution]=useState<Resolution>('auto'),[sort,setSort]=useState('profit');
  const [draft,setDraft]=useState(period),[dateMode,setDateMode]=useState('range');
  const [year,setYear]=useState(period.from.slice(0,4)),[month,setMonth]=useState(period.from.slice(0,7));
  const [invalid,setInvalid]=useState(false),[revision,setRevision]=useState(0),[detail,setDetail]=useState<Detail|null>(null),[activityPage,setActivityPage]=useState(0);
  const calendar=useRef<HTMLDetailsElement>(null);
  const priorPeriod=comparisonPeriod(period,comparison);
  const current=useExpenseReport(period,revision),previous=useExpenseReport(priorPeriod,revision);
  useEffect(()=>{const restore=()=>setComparison(comparisonFromSearch(location.search));window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[]);
  let model:ReturnType<typeof executiveModel>,prior:ReturnType<typeof executiveModel>|null,actual:ReturnType<typeof financialReport>|null,old:ReturnType<typeof financialReport>|null,trend:ReturnType<typeof businessTrend>;
  try {
    model=executiveModel(documents,period); prior=priorPeriod?executiveModel(documents,priorPeriod):null;
    actual=current&&!current.error?financialReport(documents,current.rows,current.categories,period):null;
    old=previous&&!previous.error&&priorPeriod?financialReport(documents,previous.rows,previous.categories,priorPeriod):null;
    trend=businessTrend(documents,actual?current!.rows:null,period,resolution);
  } catch {return <main className={s.dashboard}><h1>ภาพรวมธุรกิจ</h1><p role="alert">ข้อมูลไม่สมบูรณ์ ไม่สามารถคำนวณได้</p><button onClick={()=>{setRevision(v=>v+1);onRefresh?.();}}><RefreshCw size={16}/>ลองใหม่</button></main>;}
  const update=(next:DashboardPeriod)=>{if(!validPeriod(next)){setInvalid(true);return;}setInvalid(false);setDraft(next);setActivityPage(0);if(calendar.current)calendar.current.open=false;onPeriod(next);};
  const changeComparison=(next:Comparison)=>{setComparison(next);const url=new URL(location.href);url.searchParams.set('erpCompare',next);history.replaceState(history.state,'',`${url.pathname}${url.search}${url.hash}`);};
  const operating=actual?.operating??null,after=actual?.after??null,hasData=model.selected.length>0||(actual?.actual.count??0)>0;
  const kpis=[
    {label:'ยอดใบเสร็จรวม VAT',value:model.revenue,old:prior?.revenue??null,icon:ChartNoAxesColumnIncreasing,color:'amber',key:'revenue',info:'ใบเสร็จที่ไม่ถูกลบหรือยกเลิก รวมฉบับร่างตามฐานเดิม หลังส่วนลด รวม VAT ไม่ใช่เงินสดรับ',action:()=>setDetail({title:'ยอดใบเสร็จในช่วงที่เลือก',rows:model.receipts,comparisonRows:prior?.receipts})},
    {label:'กำไรขั้นต้นประมาณการ',value:model.gross,old:prior?.gross??null,icon:Banknote,color:'blue',key:'gross',info:'ยอดใบเสร็จรวม VAT หักต้นทุนประมาณการสินค้าและค่าใช้จ่ายในเอกสารตามสูตรเดิม',action:()=>setDetail({title:'ที่มากำไรขั้นต้นประมาณการ',rows:model.receipts,comparisonRows:prior?.receipts})},
    {label:'Margin ประมาณการ',value:model.margin,old:prior?.margin??null,icon:Percent,color:'amber',key:'margin',margin:true,info:'กำไรขั้นต้นประมาณการ ÷ ยอดใบเสร็จ × 100 เปรียบเทียบเป็นจุดเปอร์เซ็นต์',action:()=>setDetail({title:'ที่มา Margin ประมาณการ',rows:model.receipts,comparisonRows:prior?.receipts})},
    {label:'ค่าใช้จ่ายดำเนินงาน',value:operating,old:old?.operating??null,icon:Wallet,color:'red',key:'operating',inverse:true,info:'Operating ตามวันที่รายการ รวม VAT รวมเก็บถาวร ไม่รวมยกเลิก ไม่รวมต้นทุนตรง',action:()=>onExpenses({expenseClass:'operating'})},
    {label:'กำไรประมาณการหลังค่าใช้จ่าย',value:after,old:old?.after??null,icon:ChartColumnIncreasing,color:'green',key:'after',info:'กำไรขั้นต้นประมาณการ หัก Operating จริง ไม่หัก Direct ซ้ำ ไม่ใช่กำไรสุทธิ',action:()=>setDetail({title:'ผลประมาณการหลังค่าใช้จ่าย',rows:model.receipts,note:`กำไรขั้นต้น ${money(model.gross)} − ค่าใช้จ่ายดำเนินงาน ${money(operating)} = ${money(after)}`})},
  ];
  const groups=[...(actual?.actual.groups||[])].sort((a,b)=>Number(b.total)-Number(a.total));
  const products=[...model.products].sort((a,b)=>sort==='revenue'?b.revenue-a.revenue:sort==='margin'?(b.revenue>0?(b.revenue-b.cost)/b.revenue:-Infinity)-(a.revenue>0?(a.revenue-a.cost)/a.revenue:-Infinity):(b.revenue-b.cost)-(a.revenue-a.cost));
  const activities=[...model.selected].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));
  const activityPages=Math.max(1,Math.ceil(activities.length/5)),shownActivity=Math.min(activityPage,activityPages-1);
  const earliest=loadedAt&&current?.loadedAt?(loadedAt<current.loadedAt?loadedAt:current.loadedAt):null;
  const noActions=!(prior&&model.revenue<prior.revenue)&&!(old&&operating!==null&&operating>old.operating)&&!model.pending.length&&!model.overdue.length&&!model.uncertain;
  return <main className={s.dashboard}>
    <header className={s.header}><div className={s.headerTitle}><h1>ภาพรวมธุรกิจ</h1><p>สรุปผลการดำเนินงาน · {rangeText(period)}</p></div><div className={s.brandTag}><b>Make Ideas Visible</b><span>งานสะดุดแค่ไหน เรารู้ก่อนที่ธุรกิจคุณจะรู้</span></div><div className={s.filters}>
      <div className={s.segmented} aria-label="ช่วงวันที่ด่วน">{[['today','วันนี้'],['week','7 วัน'],['30days','30 วัน'],['month','เดือนนี้'],['year','ปีนี้']].map(([id,label])=><button key={id} aria-pressed={JSON.stringify(quickPeriod(id))===JSON.stringify(period)} onClick={()=>update(quickPeriod(id))}>{label}</button>)}</div>
      <details ref={calendar} className={s.calendar}><summary><CalendarDays size={16}/><span>{period.from} – {period.to}</span><ChevronDown size={14}/></summary><form onSubmit={e=>{e.preventDefault();if(dateMode==='month'){const[y,m]=month.split('-').map(Number);if(!y||!m){setInvalid(true);return;}update({from:`${month}-01`,to:new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)});}else update(dateMode==='year'?{from:`${year}-01-01`,to:`${year}-12-31`}:dateMode==='day'?{from:draft.from,to:draft.from}:draft);}}>
        <label>รูปแบบช่วงวันที่<select value={dateMode} onChange={e=>setDateMode(e.target.value)}><option value="range">ช่วงวันที่</option><option value="day">วันเดียว</option><option value="month">เลือกเดือน</option><option value="year">เลือกปี</option></select></label>
        {(dateMode==='range'||dateMode==='day')&&<label>เริ่มวันที่<input type="date" required value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label>}{dateMode==='range'&&<label>ถึงวันที่<input type="date" required value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></label>}
        {dateMode==='month'&&<label>เดือน<input type="month" required value={month} onChange={e=>setMonth(e.target.value)}/></label>}{dateMode==='year'&&<label>ปี ค.ศ.<input type="number" required min="2000" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></label>}
        {invalid&&<p role="alert">ช่วงวันที่ไม่ถูกต้อง</p>}<button className={s.primary}>ใช้ช่วงวันที่</button></form></details>
      <select aria-label="เปรียบเทียบกับ" value={comparison} onChange={e=>changeComparison(e.target.value as Comparison)}>{Object.entries(comparisons).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button title="ส่งออกและสำรองข้อมูล" aria-label="ส่งออกและสำรองข้อมูล" onClick={onExport}><DatabaseBackup size={17}/></button><button title="รีเฟรชข้อมูล" aria-label="รีเฟรชข้อมูล" onClick={()=>{setRevision(v=>v+1);onRefresh?.();}}><RefreshCw size={17}/></button>
    </div><div className={s.metadata}><span>{earliest?`ข้อมูลล่าสุด ${new Date(earliest).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}`:current?.error?'ข้อมูลค่าใช้จ่ายไม่พร้อม':'กำลังโหลดค่าใช้จ่าย...'}</span>{priorPeriod&&<span>เทียบ {rangeText(priorPeriod)}</span>}</div></header>
    {current?.error&&<div role="alert" className={s.error}>โหลดค่าใช้จ่ายไม่สำเร็จ <button onClick={()=>setRevision(v=>v+1)}>ลองใหม่</button></div>}{previous?.error&&priorPeriod&&<p role="status" className={s.warning}>ค่าใช้จ่ายช่วงเปรียบเทียบไม่พร้อม <button onClick={()=>setRevision(v=>v+1)}>ลองใหม่</button></p>}{!hasData&&actual&&<p role="status" className={s.empty}>ไม่มีข้อมูลในช่วงวันที่เลือก</p>}
    <section aria-label="ตัวเลขสำคัญ" className={s.kpis}>{kpis.map(kpi=><article key={kpi.label} className={s.kpi} data-metric={kpi.key} data-priority={kpi.key==='revenue'||kpi.key==='after'?'primary':undefined}><div className={s.kpiTop}><span className={`${s.icon} ${s[kpi.color]}`}><kpi.icon size={20} strokeWidth={2.4}/></span><span>{kpi.label}</span><Help>{kpi.info}</Help></div><button className={s.kpiValue} aria-label={`ดูรายละเอียด ${kpi.label}`} onClick={kpi.action}><strong className={kpi.value!==null&&kpi.value<0?s.negative:''}>{!hasData&&actual?'—':kpi.margin?kpi.value===null?'—':`${kpi.value.toFixed(1)}%`:money(kpi.value)}</strong></button><div className={s.kpiBottom}><Delta current={kpi.value} previous={kpi.old} margin={kpi.margin} inverse={kpi.inverse} enabled={!!priorPeriod}/><Spark data={trend.buckets} field={kpi.key} red={kpi.inverse}/></div></article>)}</section>
    <section className={s.alertBand}><h2><Bell size={19} className={s.amber}/>สิ่งที่ควรตรวจสอบ</h2><div className={s.alerts}>
      {prior&&model.revenue<prior.revenue&&<button className={s.alertDanger} onClick={()=>setDetail({title:'ยอดใบเสร็จลดลง',rows:model.receipts,comparisonRows:prior.receipts})}><ArrowDown size={25}/><span><b>ยอดใบเสร็จลดลง</b><small>ลดลง {money(prior.revenue-model.revenue)} จากช่วงเปรียบเทียบ</small></span><ArrowRight size={16}/></button>}
      {old&&operating!==null&&operating>old.operating&&<button className={s.alertWarning} onClick={()=>onExpenses({expenseClass:'operating'})}><Wallet size={25}/><span><b>ค่าใช้จ่ายดำเนินงานเพิ่มขึ้น</b><small>เพิ่ม {money(operating-old.operating)} จากช่วงเปรียบเทียบ</small></span><ArrowRight size={16}/></button>}
      {model.pending.length>0&&<button className={s.alertInfo} onClick={()=>setDetail({title:'ใบเสนอราคารอดำเนินการ',rows:model.pending})}><FileText size={25}/><span><b>ใบเสนอราคารอดำเนินการ</b><small>{model.pending.length} รายการในช่วงที่เลือก</small></span><ArrowRight size={16}/></button>}
      {model.overdue.length>0&&<button className={s.alertDanger} onClick={()=>setDetail({title:'ใบแจ้งหนี้เกินกำหนด',rows:model.overdue})}><CalendarDays size={25}/><span><b>ใบแจ้งหนี้เกินกำหนด</b><small>{model.overdue.length} รายการยังมียอดค้าง</small></span><ArrowRight size={16}/></button>}
      {model.uncertain>0&&<button className={s.alertWarning} onClick={()=>setDetail({title:'ตรวจฐานต้นทุน',rows:model.receipts.filter(doc=>doc.uncertainCost)})}><Info size={25}/><span><b>ตรวจฐานต้นทุน</b><small>{model.uncertain} เอกสารมี snapshot ศูนย์หรือไม่พร้อม</small></span><ArrowRight size={16}/></button>}{noActions&&<p className={s.positive}><CheckCircle2 size={18}/>ไม่มีรายการที่ต้องตรวจสอบในช่วงนี้</p>}
    </div></section>
    <DashboardCharts trend={trend} period={period} resolution={resolution} onResolution={setResolution} onBucket={p=>setDetail({title:'เอกสารในช่วงกราฟ',rows:model.receipts.filter(doc=>doc.date>=p.from&&doc.date<=p.to),range:p})} revenue={model.revenue} cost={model.cost} gross={model.gross} operating={operating} after={after}/>
    <div className={s.operations}>
      <section className={s.section}><div className={s.sectionHead}><h2><Wallet size={20} className={s.orange}/>ค่าใช้จ่ายจริง</h2><button aria-label="ดูรายละเอียดค่าใช้จ่าย" onClick={()=>onExpenses()}>รายละเอียด<ArrowRight size={14}/></button></div>
        {!current?<div className={s.loading} role="status"><span>กำลังโหลดค่าใช้จ่าย...</span><i className={s.skeleton}/><i className={s.skeleton}/><i className={s.skeleton}/></div>:!actual?<p role="alert">ข้อมูลยังไม่พร้อม</p>:<><div className={s.expenseMetrics}><div><b>{money(Number(actual.actual.total))}</b><small>ค่าใช้จ่ายจริง</small></div><div><b>{money(Number(actual.actual.paid))}</b><small>ชำระแล้ว</small></div><div><b className={Number(actual.actual.unpaid)>0?s.negative:''}>{money(Number(actual.actual.unpaid))}</b><small>ค้างชำระ</small></div></div>
          {groups.slice(0,4).map((group,i)=><button key={group.id} className={s.category} onClick={()=>onExpenses({category:group.id})}><span>{group.name}<b>{money(Number(group.total))}</b></span><span className={s.categoryTrack}><i style={{width:`${Number(actual.actual.total)>0?Number(group.total)/Number(actual.actual.total)*100:0}%`,background:['#ff9638','#4b98ff','#ae83ed','#23cc99'][i]}}/></span><small>{Number(actual.actual.total)>0?(Number(group.total)/Number(actual.actual.total)*100).toFixed(1):'0.0'}%</small></button>)}{groups.length===0&&<p className={s.empty}>ไม่มีค่าใช้จ่ายในช่วงนี้</p>}{groups.length>4&&<button onClick={()=>onExpenses()}>อีก {groups.length-4} หมวด<ArrowRight size={14}/></button>}
          <div className={s.costClasses}><button onClick={()=>onExpenses({expenseClass:'direct'})}>Direct {money(Number(actual.actual.classes[0].total))}</button><button onClick={()=>onExpenses({expenseClass:'operating'})}>Operating {money(operating)}</button></div><small className={s.muted}>รวมเก็บถาวร ไม่รวมยกเลิก · Direct ไม่หักซ้ำ</small></>}
      </section>
      <section className={s.section}><div className={s.sectionHead}><h2><Package size={20} className={s.orange}/>สินค้าทำกำไร</h2><select aria-label="เรียงสินค้า" value={sort} onChange={e=>setSort(e.target.value)}><option value="profit">กำไร</option><option value="revenue">ยอดขาย</option><option value="margin">Margin</option></select></div><div className={s.tableScroll}><table><thead><tr><th>สินค้า</th><th>ยอดขาย</th><th>กำไร</th><th>Margin</th></tr></thead><tbody>{products.slice(0,5).map((product,index)=><tr key={product.key}><td><button className={s.textButton} onClick={()=>setDetail({title:product.name,product,rows:model.receipts.filter(doc=>product.documentIds.includes(doc.id))})}><span className={s.rank}>{index+1}</span>{product.name}</button></td><td>{money(product.revenue)}</td><td className={product.revenue-product.cost<0?s.negative:''}>{money(product.revenue-product.cost)}</td><td><span className={s.badge}>{product.revenue>0?`${((product.revenue-product.cost)/product.revenue*100).toFixed(1)}%`:'—'}</span></td></tr>)}</tbody></table></div>{!products.length&&<p className={s.empty}>ไม่มีสินค้าในช่วงนี้</p>}<p className={s.footnote}>ประมาณการจากรายการ ก่อนส่วนลดเอกสาร</p><button onClick={()=>setDetail({title:'สินค้าทั้งหมดในช่วงที่เลือก',rows:model.receipts})}>ดูเอกสารที่มา<ArrowRight size={14}/></button></section>
      <section className={s.section}><div className={s.sectionHead}><h2><FileText size={20} className={s.blue}/>เอกสาร</h2></div><div className={s.documentGrid}>{Object.entries(types).map(([type,label])=><button key={type} data-document={type} onClick={()=>onDocuments(type)}><FileText size={20}/><span><span className={s.documentName}>{label}</span><b>{model.selected.filter(doc=>doc.type===type).length}</b><small>{type==='quote'?`รอดำเนินการ ${model.pending.length}`:type==='invoice'?`เกินกำหนด ${model.overdue.length}`:`ฉบับร่าง ${model.selected.filter(doc=>doc.type===type&&doc.status==='draft').length}`}</small></span></button>)}</div><p className={s.footnote}>เฉพาะช่วงที่เลือก ไม่รวมยกเลิก</p></section>
    </div>
    <section className={s.section}><div className={s.sectionHead}><h2><CalendarDays size={20} className={s.amber}/>รายการล่าสุด</h2><div className={s.pager}><button aria-label="รายการหน้าก่อน" disabled={shownActivity===0} onClick={()=>setActivityPage(shownActivity-1)}><ArrowLeft size={15}/></button><small>{shownActivity+1} / {activityPages}</small><button aria-label="รายการหน้าถัดไป" disabled={shownActivity+1===activityPages} onClick={()=>setActivityPage(shownActivity+1)}><ArrowRight size={15}/></button></div></div><div className={s.tableScroll}><table className={s.activityTable}><thead><tr><th>เอกสาร</th><th>ประเภท</th><th>ลูกค้า</th><th>วันที่</th><th>ยอดรวม</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{activities.slice(shownActivity*5,shownActivity*5+5).map(doc=><tr key={doc.id} className={s.activityRow} onClick={()=>setDetail({title:doc.docNo,rows:[doc]})}><td><button className={s.textButton} onClick={()=>setDetail({title:doc.docNo,rows:[doc]})}>{doc.docNo}</button></td><td>{types[doc.type]}</td><td>{doc.customerName}</td><td>{shortDate(doc.date)}</td><td>{money(doc.revenue)}</td><td><span className={s.badge} data-status={doc.status}>{statuses[doc.status]||doc.status}</span></td><td><button className={s.rowAction} aria-label={`ดูรายละเอียด ${doc.docNo}`} onClick={event=>{event.stopPropagation();setDetail({title:doc.docNo,rows:[doc]});}}><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div>{!activities.length&&<p className={s.empty}>ไม่มีเอกสารในช่วงนี้</p>}</section>
    {detail&&<DashboardDetail detail={detail} period={period} priorPeriod={priorPeriod} onClose={()=>setDetail(null)} onDocument={onDocuments}/>}
  </main>;
}
